version: "3"

services:

  nexus:
    image: sonatype/nexus3:3.20.0
    container_name: dev.nexus
    ports:
      - "8081:8081"
    volumes:
      - dev-nexus-vol:/nexus-data

  mysql:
    image: mysql:5.7
    container_name: dev.mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
 
  redis:
    image: redis:6.0.5-alpine
    container_name: redis.iuser
    ports:
      - "6379:6379"

volumes:
  dev-nexus-vol:
